//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        public int id { get; set; }
        public int numeroExpediente { get; set; }
        public System.DateTime fecha { get; set; }
        public string suceso { get; set; }
        public string lugar { get; set; }
        public string fase { get; set; }
        public string aeronave { get; set; }
        public int marca { get; set; }
        public string modelo { get; set; }
        public string matricula { get; set; }
        public string estado { get; set; }
        public bool status { get; set; }
    
        public virtual Marca Marca1 { get; set; }
    }
}
